### ISSUE TITLE
Problem updating data inside table through action

### ISSUE THREAD

**Issue by Reduced20** [Gustavinho/laravelviews.com#1]
The problem:
I want it so that when the user click on the 'validate' icon it changes the
$model->statut='En cours' to $model->statut='Validé';

Here is the action:
class Validate extends Action
{
    public $title = "Valider";

    public $icon = "check";

    public function handle($model,View $view){
        $model->update(['statut' => 'Validé']);
        $this->success();
    }

}
But everytime it always returns "Call to a member function update() on array" so what can I do?

**Comment by Gustavinho** [comment]
Hi @JusteQuelquun , could you open the issue here https://github.com/Gustavinho/laravel-views/issues ? just to keep this repo clean, thanks
